### ISSUE TITLE
clear cache for "transpose"

### ISSUE THREAD

**Issue by blbrunner** [membean/content#106]
changed vid verbiage and source/title

**Comment by MicahElliott** [comment]
cleared

**Comment by blbrunner** [comment]
the incorrect still is still up for this .... I will ask Doug to send the still my way

**Comment by blbrunner** [comment]
hey Micah ... here is a still that you can use: 
![mtm6](https://cloud.githubusercontent.com/assets/16691908/19413501/1d50d076-92fd-11e6-9c91-8d6cfed89180.jpg)

**Comment by MicahElliott** [comment]
fixed
