### ISSUE TITLE
Import vids and stills

### ISSUE THREAD

**Issue by blbrunner** [membean/content#11]
Hey Micah C:\Users\Brett\Dropbox\MS1\Last Mild500 Vids  These need to be imported.  Everything is finished for them, including sources/titles/proofing clip and still names.

**Comment by MicahElliott** [comment]
Missing vids for stills: irregular, perish, update. So I'll skip those vids.

**Comment by blbrunner** [comment]
hmmm .... that's weird.  We already have vids for "perish" and "update."
 Not sure why there were stills for those in there, so you can just delete
those stills.  Just go ahead and delete "irregular" as well ... sorry for
confusion there, and thanks for uploading these!

**Comment by blbrunner** [comment]
Sometimes Doug will throw things back into folders that I've already
deleted, so perhaps that was what happened wtih these.  Nevertheless, no
big ... we already have vids and stills for "perish" and for "update" and
we don't have to have one for "irregular" although I may have Doug look for
one of those anyway and we'll upload it next time.  :)
