### ISSUE TITLE
Cleanup S3 background folder

### ISSUE THREAD

**Issue by ragav** [membean/content#13]
Write now we have
0) bkgd 
1) bkgd2
2) bkgd3
3) bkgd2-questions 

It's not clear what these are and where new word images are being uploaded too.

**Comment by MicahElliott** [comment]
We won't do much with these for Rails2. For Rails4 we'll have a `bkgd` and `bkgd-enc` and `cons` and `cons-enc`. I'm working on doing the renames/push. Brian has already published the snippet in #membean:610

**Comment by MicahElliott** [comment]
Backgrounds with new encoding are on their way: http://cdn3.membean.com/public/images/wordimages/bkgd-enc/6c080f952a26aa879b64c5b8e46a8fe5a2d5d8ca49693cfdf7f56d8e0e4287d0.jpg

**Comment by MicahElliott** [comment]
Constellation encodings are up: http://cdn3.membean.com/public/images/wordimages/cons-enc/0f94079bb0c6716d89720256b77eed341aa8b857043b9a4f6590d2798ff9844a.png

**Comment by MicahElliott** [comment]
Copied all current bkgd and cons into s3://media1.membean.com/public/images/wordimages/bkgd/ and `/cons/`. So no number are present. Original versions are all pushed to `/public/images/wordimages/old/`.

We should freeze changing of bkgd and cons until code gets pushed to point to current areas.

So the final production areas will now be:
* `bkgd/` and `bkgd-enc/`
* `cons/` and `cons-enc/`
