### ISSUE TITLE
Typo in infirmity question

### ISSUE THREAD

**Issue by sarahraynor** [membean/content#14]
For the question: "What is an infirmity?", answer b  "It is something **it** not very well liked" 

Change "IT" to "IS"

http://support.membean.com/helpdesk/tickets/54496

http://srsly2.membean.com/questions/infirmity?qtype=mc_context

**Comment by blbrunner** [comment]
Done!  And it has propagated to MyWords so we're good.  :)

**Comment by MicahElliott** [comment]
It wasn't cleared on production servers. membean.com/... is the place to check these. I just cleared caches and is okay now.

**Comment by blbrunner** [comment]
that's weird, because I checked my mywords server and it had appeared!  why
would that be?

**Comment by blbrunner** [comment]
in fact, it was in there in about 10 seconds
