### ISSUE TITLE
Typo on "embankment"

### ISSUE THREAD

**Issue by sarahraynor** [membean/content#154]
On the study for the word "embankment," the description says "An embankment is a built up bank or ridge make of earth or stone that supports a road or holds back water" (instead of "made up of").

Located in: Definition

http://support.membean.com/helpdesk/tickets/54709

**Comment by blbrunner** [comment]
An embankment is a built-up bank or ridge made of earth or stone that supports a road or holds back water.  I've given the correct one here ...
