### ISSUE TITLE
wrong stills are up for "conceit" and "auxiliary"

### ISSUE THREAD

**Issue by blbrunner** [membean/content#183]
not sure why: all the rest are fine (this is from the 295 upload)

**Comment by MicahElliott** [comment]
Did another cf-invalidate on these and cleared caches. Fixes should appear within 30m.

**Comment by blbrunner** [comment]
hmmm ... not up yet, but I'll check again in the morning ... hopefully they
will be there by then

**Comment by blbrunner** [comment]
There are blank spaces there now only ... so the old stills are gone, but the new ones have yet to appear.

**Comment by MicahElliott** [comment]
These both look good. Please verify and close. @blbrunner
