### ISSUE TITLE
please fix Ticket #59849 in Freshdesk

### ISSUE THREAD

**Issue by blbrunner** [membean/content#191]
We should not have the distractor "elucidate" which the client pointed out (this was caused by random choice by our machine, which sometimes and luckily rarely occurs).  Please fix ASAP.  http://support.membean.com/helpdesk/tickets/59849  Note that I did not know to whom to assign this, s

**Comment by MicahElliott** [comment]
fixed, cache cleared. Please inspect @blbrunner

**Comment by blbrunner** [comment]
I'm not sure where I can check that!  Where do I access that question?

**Comment by MicahElliott** [comment]
@blbrunner Check here: http://membean.com/questions/enunciate?order_ref=mb_1600&qtype=mc_blank_definition

We're working on a feature to let you inspect for all products for all app servers.
