### ISSUE TITLE
please convert Word Empire Introduction document to Word

### ISSUE THREAD

**Issue by blbrunner** [membean/content#209]
I need this converted so that I can write up a worksheet.  I had to send this doc to your e-mails since I couldn't figure out how to attach it in Github.  It is under the subject line:  convert Word Empire Introduction document to Word

**Comment by MicahElliott** [comment]
@blbrunner I can convert this to html, text, or word doc.  None of these will be able to maintain the coloring or layout of the trees.  Are you just trying to paste content from this into something?  If so, you can copy/paste right from the PDF.  But I'll attach the text here in case that's useful.
[wordempire.txt](https://github.com/membean/content/files/554139/wordempire.txt)

**Comment by blbrunner** [comment]
Thank you, Micah.  For some reason I was NOT able to do that .... thanks!

Brett
