### ISSUE TITLE
wrong still is up for "ridicule"

### ISSUE THREAD

**Issue by blbrunner** [membean/content#21]
I will ping Doug about this

**Comment by blbrunner** [comment]
I do not seem to be able to find this clip in Dropbox (the one for ridicule): Micah--do you see it?  It's a level 1 word.

**Comment by blbrunner** [comment]
Or would it be possible to simply "pull" it so I can send a copy to Doug so he can create a still for it?

**Comment by blbrunner** [comment]
just sent you the still for "ridicule" over e-mail

**Comment by MicahElliott** [comment]
replaced it. Should be up in 30m.
