### ISSUE TITLE
update cache for the following words

### ISSUE THREAD

**Issue by blbrunner** [membean/content#217]
I made slight changed to all the context paragraphs for the following words:

naive
patronize
fidelity
sedentary
viable
placid
kinetic
impulsive
embark

Thanks!

**Comment by MicahElliott** [comment]
Should be all cleared now. I'll assume you didn't make significant changes to the first sentences to require changing context Qs.

**Comment by blbrunner** [comment]
Hi Micah ... that is correct in that I didn't make any significant changes to the first sentences.  These were minor changes, nothing to content, only to stylistic grammar.  Future tickets of this kind will operate under the same parameters.
