### ISSUE TITLE
Typo in question for "focus"

### ISSUE THREAD

**Issue by sarahraynor** [membean/content#223]
There is a typo in the question for Focus (answer A.)

![img_0107](https://cloud.githubusercontent.com/assets/16469259/20360219/b888fc46-abe7-11e6-99a6-6b7ca97b5fc1.PNG)

http://membean.com/questions/focus?qtype=mc_context

**Comment by MicahElliott** [comment]
I edited it and cleared cache.

**Comment by blbrunner** [comment]
thanks, Micah!!
