### ISSUE TITLE
Wrong pronunciation for relation

### ISSUE THREAD

**Issue by ragav** [membean/content#243]
From @kellymembean :

Pronounces the word "relaxation" http://membean.com/words/relation
Per the ticket reporting this it is also incorrect on the subsequent spelling page
http://support.membean.com/helpdesk/tickets/66888

**Comment by kellymembean** [comment]
http://support.membean.com/helpdesk/tickets/68538

**Comment by MicahElliott** [comment]
fixed; should show up in 30m.
