### ISSUE TITLE
Question for Disparity is confusing

### ISSUE THREAD

**Issue by kellymembean** [membean/content#251]
http://srsly2.membean.com/questions/disparity?qtype=mc_alternate

There are a number of tickets regarding this question and the answer is not very clear.
http://support.membean.com/helpdesk/tickets/68741
http://support.membean.com/search/all?term=disparity

**Comment by MicahElliott** [comment]
I vote to change it.  I also got hung up reading "close" as teams were close in competition though I was admittedly reading it quickly).

**Comment by blbrunner** [comment]
Hey Micah--I've changed.  Requested a cache clear.
