### ISSUE TITLE
record context paragraph and definition for entity ... 

### ISSUE THREAD

**Issue by blbrunner** [membean/content#253]
for the word "entity," I changed the last sentence of the context paragraph and also fine-tuned the definition.  please replace.

**Comment by MicahElliott** [comment]
Recorded, pushed, invalidated.  Should be showing up with new content very soon.

**Comment by blbrunner** [comment]
Micah--the context paragraph and definition are great, but you mispronounced "coelacanth."  It should be: 
SEE-luh-kanth.  http://www.dictionary.com/browse/coelacanth?s=t  Thanks!!

**Comment by MicahElliott** [comment]
That's embarrassing. I had heard our previous voice actor say it the other way a few times, and then it was stuck in my head the wrong way. Will fix tomorrow.

**Comment by blbrunner** [comment]
Great!  Thanks!

I'm a pretty enthusiastic cryptozoologist, and the coelacanth is an
interesting piece to the puzzle.

**Comment by MicahElliott** [comment]
Fixed. Give it 30m to show up.

**Comment by blbrunner** [comment]
it's there!
thanks!
