### ISSUE TITLE
please erase current background image for "consolidate" and add one of the following

### ISSUE THREAD

**Issue by blbrunner** [membean/content#37]
http://www.glaad.org/sites/default/files/exxon-mobil_logo2_f8e89%5B1%5D.jpg

http://www.middlemarketcenter.org/Media/Expert%20Perspectives%20Images/handshakeisolatedonbusin_89788.jpg

http://www.everythingpixar.com/uploads/3/8/2/4/38249737/506369_orig.jpg

Or you could use our new stash of images that Sarah and Ragav set up.  I think it is deposit photo. Credentials should be in lastpass I believe

**Comment by MicahElliott** [comment]
I see that the T-Mobile/AT&T is stretched and should be fixed. But why is Exxon/Mobile or Disney/Pixar better? The handshake stock is way too generic.

**Comment by blbrunner** [comment]
Hey Micah .. I think that this looks good now!  Thanks ....
