### ISSUE TITLE
correct migration of POS from content server to production server

### ISSUE THREAD

**Issue by blbrunner** [membean/content#5]
redo JUST the migration for parts of speech for Mobility .... for some reason some of these did not "take," and were defaulting to nouns (despite the fact that they were all correct in the content server)

**Comment by blbrunner** [comment]
some examples: vast,

**Comment by ragav** [comment]
The process is something like this:
1. Dump all words from production in mobility. 
2. Find pos of equivalent words in content server and dump it.
3. Update pos on production server. 
4. Clear out cache for these words.

**Comment by blbrunner** [comment]
OK.  Not sure why the POS didn't take--they were all correct in the content server, but didn't migrate properly into production, and subsequently into mywords.  For those that that affected, the POS always defaulted to a noun.  I presume that the cache clearing will only affect POS, correct?

**Comment by ragav** [comment]
@blbrunner, the cache clearing will only affect POS. It's likely that I missed transferring POS for mobility words. It's odd that I would have because it's the second step of the process I usually use to update,  but it's possible.  I'll have to do the exact same steps listed above.

**Comment by blbrunner** [comment]
@ragav well, that demystifies why it was happening!  Glad that this will be fixed!

**Comment by MicahElliott** [comment]
These were the bad ones:

```
v n organize
adj n outstanding
v n participate
adj n particular
v n perform
v n perish
v n permit
adj n plentiful
adj n pointless
adj n positive
v n possess
adj n practical
v n prefer
v n prepare
v n preserve
adj n previous
v n proceed
v n provide
v n purchase
v n pursue
v n recognize
v n reduce
v n refer
v n reform
v n reject
v n relate
v n relax
v n request
adj n required
v n research
v n reserve
v n resist
v n respond
v n revert
adj n rigid
adj n satisfied
adv n seldom
v n select
adj n senseless
adj n similar
v n simplify
v n solve
adj n standard
v n support
v n survive
v n sustain
adj n thermal
adj n timid
v n tolerate
v n transfer
v n transmit
adj n transparent
adj n tremendous
adj n tropical
adj n typical
v n update
adj n virtual
```

**Comment by MicahElliott** [comment]
Should all be fixed in production now. I spot-checked several on the pages and they seem fine, so maybe these are not cached? If they are, I'll need to clear for each.
